export const bodyOptions = [
  { label: "body", total: 17 , index:1, address:"/body/"},
  { label: "eyes", total: 17 , index:2, address:"/eyes/"},
  { label: "hair", total: 73 , index:3, address:"/hair/"},
  { label: "facial hair", total: 17 , index:4, address:"/facial_hair/"},
  { label: "mouth", total: 24 , index:5, address:"/mouths/"},
  { label: "eyebrows", total: 15 , index:6, address:"/eyebrows/"},
  { label: "hat", total: 28 , index:7, address:"/accessories/hats/"},
  { label: "neckwear", total: 18 , index:8, address:"/accessories/neckwear/"},
  { label: "earrings", total: 32 , index:9, address:"/accessories/earrings/"},
  { label: "glasses", total: 17 , index:10, address:"/accessories/glasses/"},
  { label: "clothing 1", total: 5 , index:11, address:"/clothes/layer_1/"},
  { label: "clothing 2", total: 5 , index:12, address:"/clothes/layer_2/"},
  { label: "clothing 3", total: 9 , index:13, address:"/clothes/layer_3/"},
];
