export const bodyOptions = [
  { id:"body", label: "body", total: 17 , index:1, address:"/body/"},
  { id:"eyes", label: "eyes", total: 17 , index:2, address:"/eyes/"},
  { id:"hair", label: "hair", total: 73 , index:3, address:"/hair/"},
  { id:"facial", label: "facial", total: 17 , index:4, address:"/facial/"},
  { id:"mouth", label: "mouth", total: 24 , index:5, address:"/mouths/"},
  { id:"eyebrows", label: "eyebrows", total: 15 , index:6, address:"/eyebrows/"},
  { id:"hat", label: "hat", total: 28 , index:7, address:"/accessories/hats/"},
  { id:"neck", label: "neckwear", total: 18 , index:8, address:"/accessories/neckwear/"},
  { id:"earrings", label: "earrings", total: 32 , index:9, address:"/accessories/earrings/"},
  { id:"glasses", label: "glasses", total: 17 , index:10, address:"/accessories/glasses/"},
  { id:"layer_1", label: "clothing 1", total: 5 , index:11, address:"/clothes/layer_1/"},
  { id:"layer_2", label: "clothing 2", total: 5 , index:12, address:"/clothes/layer_2/"},
  { id:"layer_3", label: "clothing 3", total: 9 , index:13, address:"/clothes/layer_3/"},
];
